### ISSUE TITLE
Bug: When rotating a vehicle -- the scene is zoomed in/out

### ISSUE THREAD

**Issue by arturvasilev** [inno-robolab/InnoSimulator#10]
The issue should be understandable from this video.

https://user-images.githubusercontent.com/18642264/115260705-aa770000-a13b-11eb-9ed9-49b701c0b6f5.mp4

## Steps to reproduce

1. Run sim
2. Put another vehicle with Environment editor
3. Change view with double-tapping "V"
4. Rotate vehicle with mouse wheel

## Expected behaviour

Vehicle is rotating and nothing else happens.

## Actual behaviour

When vehicle is rotating with **mouse wheel** -- the zoom is also changes.

**Comment by serjkopylov** [comment]
When vehicle is rotating with mouse wheel -- the zoom is also changes. - Поменяй на другой режим камеры.

**Comment by arturvasilev** [comment]
> When vehicle is rotating with mouse wheel -- the zoom is also changes. - Поменяй на другой режим камеры.

С таким видом удобнее следить за взаимным расположение машин. При других видах такой проблемы не наблюдается.

**Comment by arguskos** [comment]
В новом релизе такое же поведение?
Я вроде не фиксил, но не могу воспроизвести, у меня все коректно работает

**Comment by arturvasilev** [comment]
> В новом релизе такое же поведение?

Да6 такое же. 

> Я вроде не фиксил, но не могу воспроизвести, у меня все коректно работает

Вид должен быть выбран чтобы можно было вращать камеру вокруг авто. Необязательно free camera, но чтобы можно было смотреть на ego-car под разными ракурсами.
