### ISSUE TITLE
Docs or examples of InnoSimulator Python API usage?

### ISSUE THREAD

**Issue by Robotics010** [inno-robolab/InnoSimulator#3]
How can we use InnoSimulator Python API?
I have not found examples or instructions for that.

We need to run short and simple scenarios: put the car in a defined position, set the movement of the NPCvehicle and check the results.

**Comment by serjkopylov** [comment]
You can find it [here](https://github.com/inno-robolab/InnoSimulator/tree/master/innosim-python-api) with tests and docs [here](https://github.com/inno-robolab/InnoSimulator/blob/master/Docs/PythonApi.md)
