### ISSUE TITLE
npc waypoint control does not work

### ISSUE THREAD

**Issue by Robotics010** [inno-robolab/InnoSimulator#8]
InnoSimulator Version 2020.1.5

We need to define NPC behavior via waypoints for specific testing purposes, but NPC does not follow waypoints, it just stand still.

This is a default example about waypoints, but it doesn't work either.
[13-npc-follow-waypoints.zip](https://github.com/inno-robolab/InnoSimulator/files/5427550/13-npc-follow-waypoints.zip)

**Comment by serjkopylov** [comment]
Fixed in 2020.1.6
