### ISSUE TITLE
How we can add a cones, construction blocks in our test scenario?

### ISSUE THREAD

**Issue by Robotics010** [inno-robolab/InnoSimulator#9]
How we can add a construction block in our test scenario? And cones as well.

Such as this ones
![Screenshot from 2020-10-23 08-54-34](https://user-images.githubusercontent.com/16175093/96961479-6b118300-150d-11eb-91e6-8536ad814d3b.png)

**Comment by serjkopylov** [comment]
Added in 2020.1.6
